### PR TITLE
Improve Textures

### LINKED ISSUE #98: Proper Textures
ESPECIALLY for the grass and sand/ash.

### PR DESCRIPTION
**Pull request by sylv256**
## Changelog
 - Improve textures

## Todo
 - [ ] Make a gradle script that automatically removes any `.aseprite` and `.pal` files from built jars
 - [x] Dirt and Grass
 - [x] Fused Stone/Cobblestone
 - [ ] Indigo Stone/Cobblestone
 - [ ] Pearlescent Stone/Cobblestone
 - [x] Ores
 - [ ] White Sand, Corrupt Sand, Sand, and Ash
 - [ ] Asphalt
 - [ ] Ceramic
 - [ ] Magnetite Deposite
 - [ ] Allos Infused Variants
 - [ ] Return Portal
 - [ ] Allos/Manos Crystal
 - [ ] Thaisa
 - [ ] Taterbane
 - [ ] Yellow Daisy
 - [ ] Mystical Stem
 - [ ] Tussock, Red Tussock, and Frosted Tussock
 - [ ] Corrupt Stem
 - [ ] Wilted Flower
 - [ ] Kurei
 - [ ] Sakhalin Mint
 - [ ] Marigold
 - [ ] Frozen Stem
 - [ ] Mistbloom
 - [ ] Planks, Doors, Stairs, Slabs, Fences, and Fence Gates
 - [ ] Logs & Stripped Logs
 - [ ] Leaves

### CODE REVIEW

**Comment by valoeghese** [comment]
why keep the aseprite files

**Comment by sylv256** [comment]
> why keep the aseprite files

so other people can edit and use the same palettes

**Comment by sylv256** [comment]
we can probably make a gradle script that removes all of the aseprite files from built jars

**Comment by ramidzkh** [comment]
If the aesprite files are large I can exclude them from the resources

**Comment by sylv256** [comment]
> If the aesprite files are large I can exclude them from the resources

i'll give u push access hold on

**Comment by valoeghese** [comment]
Screenshot?

**Comment by valoeghese** [comment]
pls

**Comment by hYdos** [comment]
Closed due to problematic behavior with the project such as leeking lore documents.

**Pull request closed without merging**
